### PR TITLE
Updated Segregated List MMU

### PR DESCRIPTION
**Pull request by qingsenzhang**
The structure is a little messy right now but I'll clean it up after the debugging phase.

### CODE REVIEW

**Comment by fegin** [comment]
You should fix the conflict first.

**Comment by qingsenzhang** [comment]
@fegin 
I just fixed the conflict

**Comment by fegin** [comment]
Please never commit log. The latest commit contains 2 millions lines of change.

**Comment by fegin** [comment]
@PhantomPhillipe  @Sotskin  @KarlLeell When committing files, please make sure to check what files are committed. Committing log with thousands even millions lines of messages are very annoying.

**Comment by qingsenzhang** [comment]
Sorry for the inconvenience. I have deleted the log and will stop
committing logs to github.

**Comment by fegin** [comment]
Will use gpu_swap_integration as the branch to do the integration.

**Pull request closed without merging**
